New Firebase auth features
WolfgangSenff/GodotFirebase pull request #57
Opened 2021-01-08 02:33 UTC by BearDooks

This change focuses on adding some new Firebase Auth features that were missing. New features added include

* Sending a password reset email
* Deleting a User Account (As in user deletes their own account)

2021-01-08 19:10 UTC, lukehollenback approved these changes
One thing to consider is, instead of having the following duplicated quite a bit throughout the class...

```gdscript
if (is_busy == false):
  # Fire off some request...
else:
  printerr("Firebase Auth is currently busy and cannot process this request")
```

...Consider unifying this code into a single method. For example...

```gdscript
func _is_ready() -> bool:
  if is_busy:
    printerr("Firebase Auth is currently busy and cannot process this request")
    return false
  
  return true
```

...Then all of this code can be simplified to something like...

```gdscript
if _is_ready():
  # Fire off some request...
```

2021-01-08 19:10 UTC, lukehollenback commented on addons/godot-firebase/FirebaseAuth.gd
> +var update_account_request_url = "https://identitytoolkit.googleapis.com/v1/accounts:update?key=%s"
Can all of these be `const` instead of `var`?

2021-01-08 19:12 UTC, WolfgangSenff requested changes
Have to make sure you set is_busy to true before you make every request.

2021-01-08 19:14 UTC, lukehollenback commented
> Have to make sure you set is_busy to true before you make every request.

Note that you could bake this into the `_is_ready()` method that I proposed in my review so you don't have duplicate code.

2021-01-08 19:21 UTC, WolfgangSenff commented
> > Have to make sure you set is_busy to true before you make every request.
> 
> Note that you could bake this into the `_is_ready()` method that I proposed in my review so you don't have duplicate code.

I'd be okay with that, though I'd prefer the shorter: return not is_busy for the end. Not a big deal either way to me.

2021-01-10 18:55 UTC, WolfgangSenff approved these changes

2021-01-10 18:56 UTC, merged